const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting Rajasthan Specific Heritage & Cultural Seed with Verified Real Images...');

  // Clear existing data safely
  await prisma.review.deleteMany();
  await prisma.event.deleteMany();
  await prisma.place.deleteMany();
  await prisma.story.deleteMany();
  await prisma.contribution.deleteMany();

  const placesData = [
    // ==========================================
    // 1. JAIPUR (The Pink City)
    // ==========================================
    {
      title: 'Amer Fort & Sheesh Mahal',
      slug: 'amer-fort-jaipur',
      tagline: 'The crowning jewel of Kachhwaha Rajputs featuring the thousand-mirror Sheesh Mahal',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Jaipur',
      latitude: 26.9855,
      longitude: 75.8513,
      century: '1592 CE',
      dynasty: 'Kachhwaha Rajput Dynasty (Raja Man Singh I)',
      architecturalStyle: 'Hindu-Rajput & Mughal Syncretic Architecture',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/20191219_Fort_Amber%2C_Amer%2C_Jaipur_0955_9481.jpg/1280px-20191219_Fort_Amber%2C_Amer%2C_Jaipur_0955_9481.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/20191219_Fort_Amber%2C_Amer%2C_Jaipur_0955_9481.jpg/1280px-20191219_Fort_Amber%2C_Amer%2C_Jaipur_0955_9481.jpg',
      ],
      history: 'Amer Fort was the ancestral citadel of the Kachhwaha Rajputs before Sawai Jai Singh II founded Jaipur in 1727. Constructed from yellow and pink sandstone with white marble courtyards, it overlooks Maota Lake. The Sheesh Mahal within was designed so that a single oil lamp would illuminate the entire ceiling like a starry desert night.',
      folklore: 'Secret subterranean escape tunnels connect Amer Fort directly to Jaigarh Fort atop Cheel Ka Teela (Hill of Eagles), built to evacuate the royal family during sieges.',
      bestTimeToVisit: 'October to March (Early mornings or Sound & Light show at dusk)',
      timings: '8:00 AM – 5:30 PM, Night view 6:30 PM – 9:15 PM',
      entryFee: '₹100 (Indians), ₹500 (Foreign nationals)',
      howToReach: '11 km north of Jaipur city center. Easily accessible via city buses, private cabs, or auto-rickshaws along the Amer Road.',
      giTagCraft: 'Jaipur Blue Pottery & Sanganeri Hand-Block Print',
      isMajor: true,
      likesCount: 340,
      viewsCount: 3890,
    },
    {
      title: 'Hawa Mahal (Palace of Winds)',
      slug: 'hawa-mahal-jaipur',
      tagline: '953 pink sandstone jharokhas engineered to capture cooling desert cross-breezes',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Jaipur',
      latitude: 26.9239,
      longitude: 75.8267,
      century: '1799 CE',
      dynasty: 'Kachhwaha Rajput Dynasty (Maharaja Sawai Pratap Singh)',
      architecturalStyle: 'Rajput-Mughal Lattice Crown Architecture',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/East_facade_Hawa_Mahal_Jaipur_from_ground_level_%28July_2022%29_-_img_01.jpg/1280px-East_facade_Hawa_Mahal_Jaipur_from_ground_level_%28July_2022%29_-_img_01.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/East_facade_Hawa_Mahal_Jaipur_from_ground_level_%28July_2022%29_-_img_01.jpg/1280px-East_facade_Hawa_Mahal_Jaipur_from_ground_level_%28July_2022%29_-_img_01.jpg',
      ],
      history: 'Built by Lal Chand Ustad in the form of Lord Krishna’s crown, Hawa Mahal was designed for the royal purdah ladies to observe street festivals in the Johari Bazaar without being seen from outside. Its innovative venturi-effect windows kept the interior chambers naturally cool during scorching Rajasthan summers.',
      folklore: 'Despite standing five stories tall, Hawa Mahal has no traditional foundation; its curvature and pyramid geometry allow it to withstand desert winds like an anchored ship.',
      bestTimeToVisit: 'Sunrise when early golden rays bathe the pink facade',
      timings: '9:00 AM – 5:00 PM daily',
      entryFee: '₹50 (Indians), ₹200 (Foreigners)',
      howToReach: 'Located in the heart of Badi Choupad, Old Pink City. Walking distance from City Palace and Jantar Mantar.',
      giTagCraft: 'Jaipur Kundan Meenakari Jewelry & Lac Bangles',
      isMajor: true,
      likesCount: 512,
      viewsCount: 4820,
    },
    {
      title: 'Panna Meena Ka Kund (Hidden)',
      slug: 'panna-meena-ka-kund-jaipur',
      tagline: 'A hidden 16th-century geometric stepwell where no visitor can step twice on the same path',
      category: 'Stepwell',
      state: 'Rajasthan',
      district: 'Jaipur',
      latitude: 26.9859,
      longitude: 75.8569,
      century: '16th Century CE',
      dynasty: 'Meena Dynasty / Kachhwaha era',
      architecturalStyle: 'Symmetrical Octagonal Stepped Hydro-Sanctuary',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/20191219_Panna_Meena_ka_Kund_step_well%2C_Amber%2C_Jaipur%2C_1130_9630.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/b/b1/20191219_Panna_Meena_ka_Kund_step_well%2C_Amber%2C_Jaipur%2C_1130_9630.jpg',
      ],
      history: 'Tucked away near the Anokhi Museum behind Amer Fort, this subterranean marvel features zigzag crisscross stone steps painted in golden ochre hues. It served as both a cool social sanctuary for villagers and a life-sustaining reservoir during arid spells.',
      folklore: 'Locals challenge any traveler to walk down one set of steps and return on the exact same sequence without being mathematically disoriented by the symmetrical stairs.',
      bestTimeToVisit: 'Early morning (7:00 AM – 9:00 AM) before day tourists arrive',
      timings: 'Open sunrise to sunset',
      entryFee: 'Free entry',
      howToReach: '500 meters behind Amer Fort along the back village path toward Kheri Gate. Best reached on foot or via e-rickshaw from Amer.',
      giTagCraft: 'Amer Hand-Block Woodcut Printing & Dabu Mud Resist',
      isMajor: false,
      likesCount: 295,
      viewsCount: 2100,
    },
    {
      title: 'Gatore Ki Chhatriyan (Hidden)',
      slug: 'gatore-ki-chhatriyan-jaipur',
      tagline: 'Quiet royal white marble cenotaphs nestled in a secluded Aravalli mountain gorge',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Jaipur',
      latitude: 26.9405,
      longitude: 75.8364,
      century: '18th Century CE onwards',
      dynasty: 'Kachhwaha Rajput Kings of Jaipur',
      architecturalStyle: 'Indo-Saracenic & Rajput Marble Dome Architecture',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Gaitore_cenotaph.JPG',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/2/24/Gaitore_cenotaph.JPG',
      ],
      history: 'Resting in the foothills of Nahargarh Fort, Gaitore serves as the royal cremation ground for Jaipur rulers starting from Maharaja Sawai Jai Singh II. Each cenotaph (chhatri) is carved from Makrana white marble, reflecting the personal tastes, battle victories, and poetry favored by each sovereign.',
      folklore: 'The intricate cenotaph of Maharaja Madho Singh II features elephant and peacock motifs so delicately undercut in marble that they ring like faint temple bells in morning wind.',
      bestTimeToVisit: 'Morning 8:00 AM to 11:00 AM for soft shadows and silence',
      timings: '9:00 AM – 5:00 PM daily',
      entryFee: '₹30 for Indians, ₹100 for foreign visitors',
      howToReach: 'Located off Amer Road in the foothills below Nahargarh. A 15-minute auto ride from the walled city.',
      giTagCraft: 'Jaipur Hand-Carved Marble Idols & Stonemasonry',
      isMajor: false,
      likesCount: 220,
      viewsCount: 1650,
    },
    {
      title: 'Galta Ji & The Sun Temple (Hidden)',
      slug: 'galta-ji-temple-jaipur',
      tagline: 'An ancient natural freshwater mountain gorge with seven sacred kunds and mischievous macaques',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Jaipur',
      latitude: 26.9167,
      longitude: 75.8617,
      century: '15th–16th Century CE',
      dynasty: 'Founded by Saint Galav / Diwan Rao Kriparam',
      architecturalStyle: 'Havelis embedded directly into rocky mountain cliffs',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Zanana_Kund_Aur_Galta_Ji_Ka_Mandir_-_edited.jpg/1280px-Zanana_Kund_Aur_Galta_Ji_Ka_Mandir_-_edited.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Zanana_Kund_Aur_Galta_Ji_Ka_Mandir_-_edited.jpg/1280px-Zanana_Kund_Aur_Galta_Ji_Ka_Mandir_-_edited.jpg',
      ],
      history: 'Built inside a narrow mountain gap in the Aravallis, Galta Ji has drawn ascetics and rishis since prehistoric times. Natural springs bubble from the rock face into seven sacred water kunds, flowing uninterrupted even during the hottest May heatwaves.',
      folklore: 'The highest ridge houses the Surya Temple, offering the most spectacular panoramic view over Jaipur at sunrise and sunset as sacred chants echo across the gorge.',
      bestTimeToVisit: 'Sunrise or late afternoon 4:30 PM – 6:30 PM',
      timings: '5:00 AM – 8:00 PM daily',
      entryFee: 'Free entry (small donation for cameras optional)',
      howToReach: '10 km east of Jaipur. Approachable either by road through Galta Gate or via a scenic hilltop trek from Surajpol.',
      giTagCraft: 'Traditional Rajasthani Incense & Herbal Remedies',
      isMajor: false,
      likesCount: 275,
      viewsCount: 1980,
    },

    // ==========================================
    // 2. JODHPUR (The Blue City)
    // ==========================================
    {
      title: 'Mehrangarh Fort',
      slug: 'mehrangarh-fort-jodhpur',
      tagline: 'Rudyard Kipling’s "Work of Giants" perched 400 feet above the indigo city rooftops',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Jodhpur',
      latitude: 26.2982,
      longitude: 73.0189,
      century: '1459 CE',
      dynasty: 'Rathore Rajput Dynasty (Rao Jodha)',
      architecturalStyle: 'Monolithic Sheer Cliff Red Sandstone Fortress',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Mehrangarh_Fort_sanhita.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/9/99/Mehrangarh_Fort_sanhita.jpg',
      ],
      history: 'Mehrangarh is one of the largest and best-preserved fortresses in India. Its massive burnished red sandstone walls rise organically out of the volcanic rock ridge. It holds royal howdahs, palanquins, weaponry, and the world-renowned Phool Mahal (Palace of Flowers).',
      folklore: 'When Rao Jodha built the fort, he displaced a hermit named Cheeria Nathji who cursed the citadel with chronic droughts. To ward off the curse, Raja Ram Meghwal voluntarily agreed to be buried alive in the foundations, and his descendants are revered by the royal house to this day.',
      bestTimeToVisit: 'Early morning 9:00 AM or late afternoon 3:30 PM for golden rampart views',
      timings: '9:00 AM – 5:00 PM daily',
      entryFee: '₹100 (Indians), ₹600 (Foreign nationals)',
      howToReach: 'Towering above the city. Accessible by taxi, auto-rickshaw, or a scenic walking path winding up through the Blue City lanes.',
      giTagCraft: 'Jodhpur Wooden Handicrafts & Cast Iron Work',
      isMajor: true,
      likesCount: 480,
      viewsCount: 4210,
    },
    {
      title: 'Jaswant Thada',
      slug: 'jaswant-thada-jodhpur',
      tagline: 'The Taj Mahal of Marwar carved from translucent Makrana white marble',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Jodhpur',
      latitude: 26.3044,
      longitude: 73.0233,
      century: '1899 CE',
      dynasty: 'Rathore Rajput Dynasty (Maharaja Sardar Singh)',
      architecturalStyle: 'Rajput Classical White Marble Memorial',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Jaswant_Thada_Dawn.jpg/1280px-Jaswant_Thada_Dawn.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Jaswant_Thada_Dawn.jpg/1280px-Jaswant_Thada_Dawn.jpg',
      ],
      history: 'Built in memory of Maharaja Jaswant Singh II, this marble cenotaph is famous for stone sheets carved so thin that sunlight filters through them, glowing warm gold at dawn. It overlooks a peaceful lakeside garden with carved gazebos and migrating birds.',
      folklore: 'Locals believe the calm waters of the adjacent Devkund Lake have healing properties and that royal peacocks safeguard the sanctity of the memorial grounds.',
      bestTimeToVisit: 'Morning 8:00 AM – 11:00 AM',
      timings: '9:00 AM – 5:00 PM',
      entryFee: '₹30 (Indians), ₹50 (Foreigners)',
      howToReach: 'Located 1 km from Mehrangarh Fort entrance along the main ridge road.',
      giTagCraft: 'Jodhpur Jali Marble Inlay & Stone Lattice',
      isMajor: true,
      likesCount: 310,
      viewsCount: 2640,
    },
    {
      title: 'Toorji Ka Jhalra (Hidden)',
      slug: 'toorji-ka-jhalra-jodhpur',
      tagline: 'A restored 18th-century subterranean stepped reservoir hidden inside Jodhpur’s blue alleys',
      category: 'Stepwell',
      state: 'Rajasthan',
      district: 'Jodhpur',
      latitude: 26.2978,
      longitude: 73.0236,
      century: '1740s CE',
      dynasty: 'Marwar Rathore Dynasty (Queen Gulab Rai)',
      architecturalStyle: 'Traditional Marwar Stepped Water Architecture',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Toorji_Ka_Jhalra.jpg/1280px-Toorji_Ka_Jhalra.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Toorji_Ka_Jhalra.jpg/1280px-Toorji_Ka_Jhalra.jpg',
      ],
      history: 'Constructed by Queen Gulab Rai, consort of Maharaja Abhai Singh, to uphold the ancient Rajasthani tradition of royal women commissioning public hydro-engineering marvels. Descending 200 feet into the ground, it features hand-carved dancing elephants, medieval lions, and niches for oil lamps.',
      folklore: 'During the severe monsoonal droughts of the 19th century, this stepwell was the lifeblood of Jodhpur, revered as a sacred portal to the subterranean realm of the rain gods.',
      bestTimeToVisit: '7:00 AM for peaceful reflections or 7:00 PM when surrounding cafe lanterns light up',
      timings: 'Open 24 hours daily',
      entryFee: 'Free entry for all',
      howToReach: 'Located in Makrana Mohalla, 250 meters walking distance from Clock Tower (Sardar Market).',
      giTagCraft: 'Jodhpur Mojari Leather Shoes & Bandhani Textiles',
      isMajor: false,
      likesCount: 420,
      viewsCount: 3450,
    },
    {
      title: 'Mandore Gardens & Royal Cenotaphs (Hidden)',
      slug: 'mandore-gardens-jodhpur',
      tagline: 'The forgotten 6th-century capital of Marwar with grand overgrown dark stone devals',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Jodhpur',
      latitude: 26.3575,
      longitude: 73.0422,
      century: '6th Century CE onwards',
      dynasty: 'Pratihara & Rathore Dynasties',
      architecturalStyle: 'High Medieval Hindu Temple-Style Deval Shrines',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Temples_at_Mandor_%284571805346%29.jpg/1280px-Temples_at_Mandor_%284571805346%29.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Temples_at_Mandor_%284571805346%29.jpg/1280px-Temples_at_Mandor_%284571805346%29.jpg',
      ],
      history: 'Before Jodhpur was founded, Mandore was the ancient power center of Marwar. Unlike typical Rajasthani chhatris with simple domes, the royal memorials here are built like full Hindu temples with soaring shikhara spires carved from local red sandstone.',
      folklore: 'According to Hindu epic folklore, Mandore was the ancestral kingdom of Mandodari, the noble queen of Ravana in the Ramayana.',
      bestTimeToVisit: 'Morning hours when langurs play among ancient banyan trees',
      timings: '8:00 AM – 8:00 PM daily',
      entryFee: 'Free garden entry; museum ₹50',
      howToReach: '9 km north of Jodhpur railway station. Regular buses and autos run directly to Mandore Gate.',
      giTagCraft: 'Marwar Stone Sculpture & Mathaniya Red Chili Spices',
      isMajor: false,
      likesCount: 260,
      viewsCount: 1890,
    },

    // ==========================================
    // 3. UDAIPUR (The City of Lakes)
    // ==========================================
    {
      title: 'City Palace Udaipur',
      slug: 'city-palace-udaipur',
      tagline: 'The largest palace complex in Rajasthan standing majestic over the waters of Lake Pichola',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Udaipur',
      latitude: 24.5764,
      longitude: 73.6835,
      century: '1559 CE onwards',
      dynasty: 'Mewar Sisodia Rajput Dynasty (Maharana Udai Singh II)',
      architecturalStyle: 'Mewari Granite & Marble Palatial Architecture',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Udaipur_City_Palace.jpg/1280px-Udaipur_City_Palace.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Udaipur_City_Palace.jpg/1280px-Udaipur_City_Palace.jpg',
      ],
      history: 'Conceived over 400 years by 22 successive Maharanas of Mewar, City Palace blends Rajput architecture with delicate glass mosaics, mirror courtyards, and hanging rooftop gardens. It houses the world’s only crystal gallery and offers panoramic vistas of Lake Pichola.',
      folklore: 'When Maharana Udai Singh was hunting on the banks of Lake Pichola, he met a hermit on the hill who blessed him to build his citadel right there, prophesying it would never fall into enemy hands.',
      bestTimeToVisit: 'October to March (Boat ride on Lake Pichola at sunset)',
      timings: '9:00 AM – 5:30 PM daily',
      entryFee: '₹300 (Palace Museum for adults)',
      howToReach: 'Centrally located in Udaipur Old City. Walkable from Jagdish Temple or accessible by cab.',
      giTagCraft: 'Mewar Miniature Paintings & Silver Jewelry',
      isMajor: true,
      likesCount: 620,
      viewsCount: 5400,
    },
    {
      title: 'Lake Pichola & Jag Mandir',
      slug: 'lake-pichola-jag-mandir-udaipur',
      tagline: 'The serene 14th-century freshwater lake embracing the floating island marble palace',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Udaipur',
      latitude: 24.5700,
      longitude: 73.6792,
      century: '1362 CE',
      dynasty: 'Founded by Banjara tribesman Pichhu / Mewar expansion',
      architecturalStyle: 'Island Marble Pavilion & Carved Stone Elephants',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Udaipur_Lake_India.JPG/1280px-Udaipur_Lake_India.JPG',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Udaipur_Lake_India.JPG/1280px-Udaipur_Lake_India.JPG',
      ],
      history: 'Built originally by a gypsy Banjara grain merchant to transport grain across streams, Maharana Udai Singh later enlarged the lake by building a masonry dam at Badipol. Jag Mandir island palace within served as a sanctuary for Mughal Prince Khurram (later Emperor Shah Jahan) in 1623, inspiring his architectural vision for the Taj Mahal.',
      folklore: 'The marble elephants standing guard at the water’s edge of Jag Mandir were sculpted to honor the royal war elephants that carried food and supplies across the water during sieges.',
      bestTimeToVisit: 'Sunset boat cruise 4:30 PM – 6:00 PM',
      timings: 'Boats operate 9:00 AM – 6:00 PM',
      entryFee: '₹400–₹800 (Boat cruise including island entry)',
      howToReach: 'Accessible via Rameshwar Ghat inside the City Palace complex or Gangaur Ghat.',
      giTagCraft: 'Udaipur Stone Enamel & Pichwai Art',
      isMajor: true,
      likesCount: 590,
      viewsCount: 4800,
    },
    {
      title: 'Ahar Royal Cenotaphs (Hidden)',
      slug: 'ahar-cenotaphs-udaipur',
      tagline: 'Over 250 white marble and sandstone chhatris honoring Mewar kings across five centuries',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Udaipur',
      latitude: 24.5886,
      longitude: 73.7197,
      century: '15th–19th Century CE',
      dynasty: 'Mewar Sisodia Dynasty',
      architecturalStyle: 'Carved Fluted Columns & Stepped Domes',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/1919_Cenatoph_of_Pannalal_at_Mahasatiya_in_Udaipur.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/6/6b/1919_Cenatoph_of_Pannalal_at_Mahasatiya_in_Udaipur.jpg',
      ],
      history: 'Ahar was a thriving copper-age civilization dating back to 2000 BCE. Later, the rulers of Mewar built their royal cremation memorials here. The most magnificent is the cenotaph of Maharana Amar Singh I, featuring a four-faced marble idol and 56 delicately sculpted pillars.',
      folklore: 'Archaeologists working in Ahar unearthed copper axes and pottery older than the Indus Valley civilization, leading historians to call it the cradle of Mewari identity.',
      bestTimeToVisit: 'Quiet afternoons or mornings before 11:00 AM',
      timings: '6:00 AM – 6:00 PM daily',
      entryFee: 'Free entry (Museum ₹20)',
      howToReach: 'Located in Ahar, 3 km east of Udaipur center. A quick 10-minute auto-rickshaw ride.',
      giTagCraft: 'Mewar Stone Sculpture & Block Print Fabrics',
      isMajor: false,
      likesCount: 215,
      viewsCount: 1720,
    },

    // ==========================================
    // 4. JAISALMER (The Golden City)
    // ==========================================
    {
      title: 'Jaisalmer Fort (Sonar Qila)',
      slug: 'jaisalmer-fort',
      tagline: 'The world’s only living golden sandstone fort housing 4,000 residents inside medieval bastions',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Jaisalmer',
      latitude: 26.9124,
      longitude: 70.9127,
      century: '1156 CE',
      dynasty: 'Bhati Rajput Dynasty (Rawal Jaisal)',
      architecturalStyle: 'Golden Yellow Sandstone Medieval Hilltop Citadel',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Jaisalmer_forteresse.jpg/1280px-Jaisalmer_forteresse.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Jaisalmer_forteresse.jpg/1280px-Jaisalmer_forteresse.jpg',
      ],
      history: 'Rising like a mirage from the Thar Desert atop Trikuta Hill, Jaisalmer Fort was a crucial crossroads on the ancient Silk Route. Its walls are assembled without mortar, using interlocking yellow sandstone slabs that change color from tawny lion at midday to burnished gold at sunset.',
      folklore: 'Satyajit Ray immortalized this fort in his legendary detective thriller "Sonar Kella" (The Golden Fortress), forever making it a beacon of mystery and treasure lore.',
      bestTimeToVisit: 'October to February (Sunset walk along the 99 bastions)',
      timings: 'Fort lanes open 24 hours; Palace Museum 9:00 AM – 6:00 PM',
      entryFee: 'Free to enter the living fort; Palace Museum ₹100',
      howToReach: 'Located directly in the center of Jaisalmer city, walking distance from the main market.',
      giTagCraft: 'Jaisalmer Yellow Marble Handcrafts & Camel Leather Bags',
      isMajor: true,
      likesCount: 580,
      viewsCount: 4950,
    },
    {
      title: 'Patwon Ki Haveli',
      slug: 'patwon-ki-haveli-jaisalmer',
      tagline: 'A cluster of five five-storey golden sandstone havelis with lace-like filigree carving',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Jaisalmer',
      latitude: 26.9144,
      longitude: 70.9167,
      century: '1805–1860 CE',
      dynasty: 'Guman Chand Patwa (Wealthy Brocade & Opium Merchant)',
      architecturalStyle: 'Yellow Sandstone Jali & Lattice Carving',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Patwon_Ki_Haveli_Jaisalmer.JPG',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/0/0c/Patwon_Ki_Haveli_Jaisalmer.JPG',
      ],
      history: 'Commissioned by wealthy merchant Guman Chand Patwa for his five sons, this monumental cluster took 55 years to sculpt. The facade features over 60 intricately carved jharokhas, each sculpted with different floral and geometric patterns that resemble delicate hand embroidery.',
      folklore: 'The Patwa family made their vast wealth trading gold threads (zari), silver, and precious opium caravans across Persia, Egypt, and Central Asia.',
      bestTimeToVisit: 'Morning 9:00 AM – 12:00 PM',
      timings: '9:00 AM – 6:00 PM daily',
      entryFee: '₹100 (Indians), ₹250 (Foreigners)',
      howToReach: 'Located in a narrow lane in the old city below the fort. 10-minute walk from Gadisar Lake.',
      giTagCraft: 'Jaisalmer Hand-Embroidered Zari & Mirror Work',
      isMajor: true,
      likesCount: 450,
      viewsCount: 3750,
    },
    {
      title: 'Kuldhara Abandoned Ghost Village (Hidden)',
      slug: 'kuldhara-abandoned-village-jaisalmer',
      tagline: 'The eerie 13th-century desert settlement vacated overnight by 84 Paliwal Brahmin clans',
      category: 'Rock Art & Caves',
      state: 'Rajasthan',
      district: 'Jaisalmer',
      latitude: 26.8689,
      longitude: 70.7878,
      century: '13th Century CE (Abandoned 1825)',
      dynasty: 'Paliwal Brahmin Agricultural Guild',
      architecturalStyle: 'Desert Grid Stone Houses & Rainwater Harvesting Wells',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Kuldhara%2C_an_abandoned_village_%2830738705327%29.jpg/1280px-Kuldhara%2C_an_abandoned_village_%2830738705327%29.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Kuldhara%2C_an_abandoned_village_%2830738705327%29.jpg/1280px-Kuldhara%2C_an_abandoned_village_%2830738705327%29.jpg',
      ],
      history: 'Kuldhara was once an affluent community of ingenious farmers who mastered desert gypsum-bed agriculture. In 1825, under persecution from the tyrannical prime minister Salim Singh, the entire population of Kuldhara and 84 neighboring villages vanished in a single night without a trace.',
      folklore: 'Before departing, the elders cast an unbreakable curse upon the earth that no one would ever be able to settle or build a life in Kuldhara again. To this day, the ruined sandstone homes stand uninhabited under the desert wind.',
      bestTimeToVisit: '4:00 PM to 6:00 PM (Visitors must leave before dark per ASI rules)',
      timings: '8:00 AM – 6:00 PM daily',
      entryFee: '₹50 per person, ₹50 for vehicle',
      howToReach: '18 km southwest of Jaisalmer on the road to Sam Sand Dunes. Accessible by private taxi or rental bike.',
      giTagCraft: 'Paliwal Ancient Stone Mortar & Traditional Woolen Shawls',
      isMajor: false,
      likesCount: 410,
      viewsCount: 3200,
    },
    {
      title: 'Bada Bagh Royal Desert Cenotaphs (Hidden)',
      slug: 'bada-bagh-jaisalmer',
      tagline: 'Golden sandstone chhatris overlooking an ancient desert dam under vast open skies',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Jaisalmer',
      latitude: 26.9622,
      longitude: 70.8872,
      century: '16th–20th Century CE',
      dynasty: 'Bhati Dynasty of Jaisalmer (Maharawal Jait Singh)',
      architecturalStyle: 'Desert Rajput Cenotaph Architecture',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Resting_places.jpg/1280px-Resting_places.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Resting_places.jpg/1280px-Resting_places.jpg',
      ],
      history: 'Commissioned by Maharawal Jait Singh, who created a stone dam to foster an oasis (Bada Bagh) in the hyper-arid Thar Desert. Upon his passing, his son built the first cenotaph here. Subsequent kings added carved chhatris featuring equestrian and warrior stele carvings.',
      folklore: 'The wind whipping through the carved domes produces eerie, resonant musical hums that desert nomads interpreted as ancestral blessings.',
      bestTimeToVisit: 'Golden hour (5:00 PM – 6:30 PM) for deep orange sunset glows',
      timings: '8:00 AM – 6:30 PM daily',
      entryFee: '₹100 (Indians), ₹300 (Foreigners)',
      howToReach: '6 km north of Jaisalmer off the Ramgarh Road. 15 minutes by auto or taxi.',
      giTagCraft: 'Jaisalmer Fossil Stone Carvings (Habur Stone)',
      isMajor: false,
      likesCount: 330,
      viewsCount: 2450,
    },

    // ==========================================
    // 5. BUNDI (The Stepwell Capital)
    // ==========================================
    {
      title: 'Taragarh Fort & Garh Palace Bundi',
      slug: 'taragarh-fort-bundi',
      tagline: 'The dream-like cliffside palace Kipling described as "built by goblins rather than men"',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Bundi',
      latitude: 25.4489,
      longitude: 75.6322,
      century: '1354 CE',
      dynasty: 'Hada Chauhan Rajput Dynasty (Rao Bar Singh)',
      architecturalStyle: 'Medieval Hilltop Fortress & Rajput Murals',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Garh_Palace_and_Taragarh_Fort%2C_Bundi_2011-12-26_EK_II.jpg/1280px-Garh_Palace_and_Taragarh_Fort%2C_Bundi_2011-12-26_EK_II.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Garh_Palace_and_Taragarh_Fort%2C_Bundi_2011-12-26_EK_II.jpg/1280px-Garh_Palace_and_Taragarh_Fort%2C_Bundi_2011-12-26_EK_II.jpg',
      ],
      history: 'Taragarh (Star Fort) crowns a steep 1,426-foot hill above Bundi. It was virtually impregnable due to its massive subterranean water reservoirs (bhuris) and its famous 16th-century brass cannon, the Garbh Gunjam. Bundi Palace below holds some of the finest untouched frescoes in Asia.',
      folklore: 'Local legend says subterranean chambers hold the fabled treasure of the Hada kings, sealed beneath gigantic iron trapdoors guarded by spirits.',
      bestTimeToVisit: 'Morning trek 8:00 AM – 11:00 AM',
      timings: '8:00 AM – 5:00 PM',
      entryFee: '₹100 for palace & fort entry',
      howToReach: 'Bundi is 35 km from Kota railway hub. Easy buses and taxis connect Kota to Bundi in 45 minutes.',
      giTagCraft: 'Bundi School of Miniature Paintings (Bundi Kalam)',
      isMajor: true,
      likesCount: 370,
      viewsCount: 3100,
    },
    {
      title: 'Raniji Ki Baori (Queen’s Stepwell) (Hidden)',
      slug: 'raniji-ki-baori-bundi',
      tagline: 'The undisputed masterpiece of Rajasthani stepwells with 50-foot carved arched toranas',
      category: 'Stepwell',
      state: 'Rajasthan',
      district: 'Bundi',
      latitude: 25.4414,
      longitude: 75.6419,
      century: '1699 CE',
      dynasty: 'Hada Rajput Dynasty (Rani Nathavati)',
      architecturalStyle: 'Multi-Storey Sculptural Stepped Hydro-Sanctuary',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Rani_ji_ki_Baori_Bundi.jpg/1280px-Rani_ji_ki_Baori_Bundi.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Rani_ji_ki_Baori_Bundi.jpg/1280px-Rani_ji_ki_Baori_Bundi.jpg',
      ],
      history: 'Built by the younger queen Rani Nathavati, who gave birth to Rao Raja Budh Singh, this 46-meter-deep stepwell is the most celebrated of Bundi’s 50+ baoris. Its soaring stone gateway features high-relief carvings of Lord Ganesha, Vishnu’s ten avatars, and slender elephant toranas.',
      folklore: 'The underground chambers were cooled by continuous subterranean spring currents, allowing queens to read classical poetry during summer heatwaves.',
      bestTimeToVisit: 'Morning 9:00 AM to noon for direct sunlight down the stepped shaft',
      timings: '9:00 AM – 5:00 PM daily',
      entryFee: '₹50 (Indians), ₹200 (Foreigners)',
      howToReach: 'Located near the center of Bundi town, walking distance from the main market.',
      giTagCraft: 'Bundi Brass Bells & Hand-Carved Wooden Printing Blocks',
      isMajor: false,
      likesCount: 390,
      viewsCount: 2890,
    },
    {
      title: 'Chitrashala (The Painted Palace) (Hidden)',
      slug: 'chitrashala-painted-palace-bundi',
      tagline: 'A hidden gallery of 18th-century turquoise, gold, and mineral frescoes untouched by modern light',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Bundi',
      latitude: 25.4497,
      longitude: 75.6335,
      century: '18th Century CE (reign of Umaid Singh)',
      dynasty: 'Hada Rajput Bundi Court',
      architecturalStyle: 'Intricate Rajput Miniature Murals on Lime Plaster',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Chitrashala%2C_Garh_Palace%2C_Bundi%2C_Rajasthan.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/f/f8/Chitrashala%2C_Garh_Palace%2C_Bundi%2C_Rajasthan.jpg',
      ],
      history: 'Perched above the Garh Palace, Chitrashala is an open courtyard surrounded by galleries entirely covered in vibrant murals. The paintings depict scenes from the Raslila, royal polo matches, monsoon processions, and divine court scenes rendered with natural copper, lapis lazuli, and pure gold leaf pigments.',
      folklore: 'The distinctive glowing turquoise green pigment used throughout Chitrashala was concocted using secret crushed mineral ores from the Chambal valley that have remained unfaded for over 250 years.',
      bestTimeToVisit: '10:00 AM – 2:00 PM for natural ambient courtyard lighting',
      timings: '8:00 AM – 5:00 PM daily',
      entryFee: 'Included with Bundi Palace ticket',
      howToReach: 'Ascend the stone ramp from Bundi Palace entrance; Chitrashala is at the top tier.',
      giTagCraft: 'Natural Mineral Pigment Art & Bundi Miniature School',
      isMajor: false,
      likesCount: 310,
      viewsCount: 2400,
    },

    // ==========================================
    // 6. PUSHKAR & AJMER (Sacred Oasis & Sufi Shrine)
    // ==========================================
    {
      title: 'Pushkar Sacred Lake & 52 Ghats',
      slug: 'pushkar-sacred-lake',
      tagline: 'The sacred oasis born from Lord Brahma’s lotus petal surrounded by 400 blue and white temples',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Pushkar',
      latitude: 26.4897,
      longitude: 74.5511,
      century: 'Ancient Antiquity (Temples rebuilt 18th Century CE)',
      dynasty: 'Paramara & Maratha Dynasties',
      architecturalStyle: 'Octagonal Ghat Steps & Classical Rajput Sanctuaries',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Evening_lights_by_the_Pushkar_Lake%2C_Pushkar.jpg/1280px-Evening_lights_by_the_Pushkar_Lake%2C_Pushkar.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Evening_lights_by_the_Pushkar_Lake%2C_Pushkar.jpg/1280px-Evening_lights_by_the_Pushkar_Lake%2C_Pushkar.jpg',
      ],
      history: 'Pushkar is one of the five sacred dhams in Hinduism and the site of the world’s rare Lord Brahma temple. 52 stone ghats embrace the holy lake where pilgrims from across Rajasthan gather at dawn for prayers and evening aarti as thousands of oil lamps float across the water.',
      folklore: 'Legend states that Lord Brahma dropped a blue lotus (pushpa) from heaven, and water gushed forth to form the lake, giving the town its immortal name: Pushkar.',
      bestTimeToVisit: 'Sunset 5:30 PM for Maha Aarti, or during the annual November Kartik Purnima Camel Fair',
      timings: 'Open 24 hours (Aarti at 6:30 PM)',
      entryFee: 'Free entry for all',
      howToReach: '14 km over the Nag Pahar mountain pass from Ajmer railway junction. Frequent taxis and buses connect both towns in 30 minutes.',
      giTagCraft: 'Pushkar Pure Rose Water & Gulkand Delicacies',
      isMajor: true,
      likesCount: 460,
      viewsCount: 3900,
    },
    {
      title: 'Ajmer Sharif Dargah',
      slug: 'ajmer-sharif-dargah',
      tagline: 'The revered 13th-century Sufi shrine of Khwaja Moinuddin Chishti visited by millions of seekers',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Ajmer',
      latitude: 26.4562,
      longitude: 74.6289,
      century: '13th Century CE',
      dynasty: 'Sultanate & Mughal Patronage (Akbar & Shah Jahan)',
      architecturalStyle: 'Indo-Islamic Marble Domed Shrine Architecture',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/2/25/Ajmer_Sharif_Dargah.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/2/25/Ajmer_Sharif_Dargah.jpg',
      ],
      history: 'Resting at the foot of Taragarh hill in Ajmer, this world-renowned sanctuary is the resting place of Sufi saint Hazrat Khwaja Moinuddin Chishti. Emperor Akbar walked on foot from Agra to Ajmer multiple times to seek blessings here. The giant cauldrons (degs) prepare communal vegetarian food for thousands daily.',
      folklore: 'The mystical qawwali performances held in the courtyard on Thursday nights are believed to induce deep spiritual trance and unite travelers regardless of faith or caste.',
      bestTimeToVisit: 'Early morning 6:00 AM or Thursday evening for soulful Qawwali',
      timings: '5:00 AM – 9:00 PM daily',
      entryFee: 'Free entry for all',
      howToReach: 'Located 2 km from Ajmer Junction railway station. Readily accessible by auto-rickshaws through the bazaar.',
      giTagCraft: 'Ajmer Ittar (Natural Perfumes) & Velvet Chaddar Embroidery',
      isMajor: true,
      likesCount: 520,
      viewsCount: 4300,
    },
    {
      title: 'Savitri Devi Hilltop Temple (Hidden)',
      slug: 'savitri-devi-temple-pushkar',
      tagline: 'A steep sunrise pilgrimage climb atop Ratnagiri Hill overlooking the desert expanse',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Pushkar',
      latitude: 26.4822,
      longitude: 74.5422,
      century: 'Ancient Shrine',
      dynasty: 'Gupta & Rajput eras',
      architecturalStyle: 'Hilltop Fortress Temple',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/6/69/Hill_top_temple%2C_overlooking_Pushkar_lake%2C_Rajasthan.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/6/69/Hill_top_temple%2C_overlooking_Pushkar_lake%2C_Rajasthan.jpg',
      ],
      history: 'Dedicated to Goddess Savitri, the consort of Brahma who retreated to this high peak after a celestial disagreement. Today, a 1.5 km stone stairway and a modern ropeway lead to the summit, offering the most breathtaking panoramic views over the desert dunes and sacred lake below.',
      folklore: 'Tradition dictates that a pilgrimage to Pushkar is complete only after paying homage at Savitri Temple following prayers at Brahma Temple.',
      bestTimeToVisit: 'Sunrise 5:30 AM to see dawn break over the desert hills',
      timings: '5:00 AM – 7:00 PM daily',
      entryFee: 'Free entry; ropeway cable car ₹150 return',
      howToReach: 'Located on Ratnagiri Hill, 2 km southwest of Pushkar town center.',
      giTagCraft: 'Traditional Pushkar Brass Trinkets & Leather Journals',
      isMajor: false,
      likesCount: 240,
      viewsCount: 1950,
    },

    // ==========================================
    // 7. BIKANER (The Red Sandstone Citadel)
    // ==========================================
    {
      title: 'Junagarh Fort',
      slug: 'junagarh-fort-bikaner',
      tagline: 'The impregnable desert fortress built not on a hill, but on the open plains of Thar',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Bikaner',
      latitude: 28.0222,
      longitude: 73.3197,
      century: '1589–1594 CE',
      dynasty: 'Rathore Dynasty (Raja Rai Singh)',
      architecturalStyle: 'Red Sandstone & Marble Indo-Mughal Fortress',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/India_Bikaner_Junagarh_Fort.jpg/1280px-India_Bikaner_Junagarh_Fort.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/India_Bikaner_Junagarh_Fort.jpg/1280px-India_Bikaner_Junagarh_Fort.jpg',
      ],
      history: 'Originally called Chintamani, Junagarh is one of the few major forts in Rajasthan not constructed on a hilltop. Despite facing dozens of sieges across four centuries, it was never captured, except for a brief single-day occupation by Kamran Mirza in 1534. It features magnificent Badal Mahal courtyards painted with blue monsoon clouds.',
      folklore: 'The Badal Mahal (Cloud Palace) was painted with celestial storm clouds, lightning bolts, and rain motifs so the desert kings could experience the psychological illusion of a monsoon downpour year-round.',
      bestTimeToVisit: 'October to March (10:00 AM – 4:00 PM)',
      timings: '10:00 AM – 4:30 PM daily',
      entryFee: '₹50 (Indians), ₹300 (Foreigners)',
      howToReach: 'Located in the heart of Bikaner city, 1.5 km from Bikaner Railway Station.',
      giTagCraft: 'Bikaner Usta Art (Embossed Gold Foil on Camel Leather)',
      isMajor: true,
      likesCount: 410,
      viewsCount: 3500,
    },
    {
      title: 'Rampuria Havelis (Hidden)',
      slug: 'rampuria-havelis-bikaner',
      tagline: 'Centuries-old red Dulmera sandstone merchant mansions with Victorian-Rajput filigree',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Bikaner',
      latitude: 28.0167,
      longitude: 73.3089,
      century: '19th–20th Century CE',
      dynasty: 'Rampuria Wealthy Jain Merchant Family',
      architecturalStyle: 'Dulmera Red Sandstone Jali & Baroque Syncretism',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Rampuria_Haveli%2C_Bikaner.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/9/94/Rampuria_Haveli%2C_Bikaner.jpg',
      ],
      history: 'Constructed by the aristocratic merchant Rampuria family, these contiguous havelis in the narrow alleys of Bikaner old city represent the zenith of desert stonemasonry. Crafted from vibrant red Dulmera sandstone, the facades feature carved dancing angels, Roman pediments, and traditional Rajasthani jharokhas.',
      folklore: 'The merchants imported Italian glass, Belgian chandeliers, and British tiles that were transported across hundreds of miles of sand dunes by camel caravans to outshine rival traders.',
      bestTimeToVisit: 'Early morning 7:30 AM before market traffic crowds the tight lanes',
      timings: 'Exterior viewable 24 hours; some havelis operate as boutique stays',
      entryFee: 'Free exterior walking tour',
      howToReach: 'Located in Joshiwara, Old City Bikaner. Best explored on foot or by cycle rickshaw from Kote Gate.',
      giTagCraft: 'Bikaner Miniature Painting & Traditional Bhujia Guilds',
      isMajor: false,
      likesCount: 340,
      viewsCount: 2600,
    },
    {
      title: 'Bhandasar Jain Temple (Hidden)',
      slug: 'bhandasar-jain-temple-bikaner',
      tagline: 'A 15th-century three-storey temple whose foundation was laid with 40,000 kilograms of pure ghee',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Bikaner',
      latitude: 28.0139,
      longitude: 73.3022,
      century: '1468–1514 CE',
      dynasty: 'Commissioned by Merchant Bhandasa Oswal',
      architecturalStyle: 'Three-Storey Yellow Sandstone & Pure Gold Leaf Murals',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Bhandasar_Jain_temple_exterior_-_1.jpg/1280px-Bhandasar_Jain_temple_exterior_-_1.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Bhandasar_Jain_temple_exterior_-_1.jpg/1280px-Bhandasar_Jain_temple_exterior_-_1.jpg',
      ],
      history: 'Dedicated to the 5th Tirthankara, Sumatinatha, this temple is famous throughout India because its builder, the wealthy merchant Bhandasa, used 40,000 kg of clarified butter (desi ghee) in place of water in the foundation mortar to ensure its structural permanence in desert dry earth.',
      folklore: 'During the sweltering heat of June, locals say droplets of ghee still seep microscopically through the stone floor tiles, perfuming the sanctum with sweet aroma.',
      bestTimeToVisit: 'Morning 8:00 AM – 11:00 AM for view of Bikaner from top tier',
      timings: '6:00 AM – 6:00 PM daily',
      entryFee: 'Free entry (small donation appreciated)',
      howToReach: '5 km from Bikaner Railway Station, nestled inside the old walled city near Laxminath Temple.',
      giTagCraft: 'Bikaner Wood Inlay & Hand-Painted Lac Bangles',
      isMajor: false,
      likesCount: 280,
      viewsCount: 2150,
    },

    // ==========================================
    // 8. SHEKHAWATI (Mandawa & Nawalgarh)
    // ==========================================
    {
      title: 'Mandawa Castle Fort',
      slug: 'mandawa-castle-fort',
      tagline: 'The painted fortress at the center of Shekhawati’s world-renowned open-air art gallery',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Shekhawati',
      latitude: 28.0556,
      longitude: 75.1436,
      century: '1755 CE',
      dynasty: 'Shekhawat Rajput Dynasty (Thakur Nawal Singh)',
      architecturalStyle: 'Fortified Rajasthani Castle & Wall Frescoes',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Haveli_mandawa.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/0/0b/Haveli_mandawa.jpg',
      ],
      history: 'Founded by Thakur Nawal Singh, Mandawa grew as a vital silk and spice trading outpost. The central castle fort features medieval painted archways, Lord Krishna murals, and an armory room with ceremonial talwars and shields.',
      folklore: 'Local merchants would hire artists to depict modern Western inventions like aeroplanes, vintage motorcars, and gramophones on the walls alongside gods to signal their international business connections.',
      bestTimeToVisit: 'October to March',
      timings: '9:00 AM – 6:00 PM daily',
      entryFee: '₹150 for non-staying day visitors',
      howToReach: 'Mandawa is 168 km from Jaipur (3.5 hours by road) and 28 km from Jhunjhunu.',
      giTagCraft: 'Shekhawati Wood Carving & Fresco Restoration Techniques',
      isMajor: true,
      likesCount: 360,
      viewsCount: 2800,
    },
    {
      title: 'Dr. Ramnath A. Poddar Haveli Museum (Hidden)',
      slug: 'poddar-haveli-nawalgarh',
      tagline: 'A restored twin haveli boasting over 750 brilliant original wall frescoes in Nawalgarh',
      category: 'Living Crafts & Handloom',
      state: 'Rajasthan',
      district: 'Shekhawati',
      latitude: 27.8508,
      longitude: 75.2711,
      century: '1902 CE',
      dynasty: 'Poddar Marwari Trading House',
      architecturalStyle: 'Traditional Rajasthani Courtyard Haveli with Frescoes',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Morarka_Haveli_Museum%2C_Nawalgarh_-_12.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/6/67/Morarka_Haveli_Museum%2C_Nawalgarh_-_12.jpg',
      ],
      history: 'Built by Anandilal Hemraj Poddar, this opulent haveli has been meticulously preserved as a cultural museum. Its inner courtyards showcase rare wet-lime (fresco buono) murals depicting scenes from Indian mythology, royal processions, and early 20th-century steam trains.',
      folklore: 'The master painters (chiteras) prepared natural dyes using lamp soot for black, crushed turmeric for yellow, cinnabar for red, and indigo for rich blues that have survived without flaking.',
      bestTimeToVisit: 'November to February for pleasant walking weather',
      timings: '8:30 AM – 6:30 PM daily',
      entryFee: '₹100 (Indians), ₹300 (Foreigners)',
      howToReach: 'Located in Nawalgarh, 30 km from Sikar and 140 km from Jaipur. Easily reachable by express bus or car.',
      giTagCraft: 'Shekhawati Hand-Woven Woolen Durries & Tie-Dye Turbans',
      isMajor: false,
      likesCount: 290,
      viewsCount: 2310,
    },

    // ==========================================
    // 9. CHITTORGARH & KUMBHALGARH (Valor & The Great Wall)
    // ==========================================
    {
      title: 'Chittorgarh Fort & Vijay Stambha',
      slug: 'chittorgarh-fort',
      tagline: 'The largest fort in India and UNESCO World Heritage site embodying supreme Rajput valor',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Chittorgarh',
      latitude: 24.8879,
      longitude: 74.6455,
      century: '7th Century CE onwards',
      dynasty: 'Mori & Sisodia Rajput Dynasties',
      architecturalStyle: 'High Plateau Monolithic Stone Fortification',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Chittorgarh_fort.JPG/1280px-Chittorgarh_fort.JPG',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Chittorgarh_fort.JPG/1280px-Chittorgarh_fort.JPG',
      ],
      history: 'Sprawled over 700 acres atop a 590-foot hill, Chittorgarh was the historic capital of Mewar. It witnessed legendary battles and three historic Jauhars led by Rani Padmini and Rani Karnavati. The nine-storey Vijay Stambha (Tower of Victory) was erected by Rana Kumbha in 1448 to commemorate his victory over Mahmud Khilji.',
      folklore: 'The subterranean reservoir Gaumukh Kund is fed by an underground natural fissure that flows constantly from a carved cow’s mouth, regarded as holy as the Ganga by Mewari warriors.',
      bestTimeToVisit: 'Early morning 8:00 AM – 1:00 PM',
      timings: '9:00 AM – 5:00 PM daily',
      entryFee: '₹40 (Indians), ₹600 (Foreigners)',
      howToReach: 'Chittorgarh is well-connected by train from Udaipur (115 km) and Jaipur (310 km).',
      giTagCraft: 'Thewa Gold Jewelry & Akola Dabu Hand-Block Print',
      isMajor: true,
      likesCount: 540,
      viewsCount: 4620,
    },
    {
      title: 'Kumbhalgarh Fort (The Great Wall of India)',
      slug: 'kumbhalgarh-fort',
      tagline: 'The impenetrable birthplace of Maharana Pratap boasting a 36-kilometer continuous defensive wall',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Kumbhalgarh',
      latitude: 25.1528,
      longitude: 73.5872,
      century: '15th Century CE',
      dynasty: 'Mewar Sisodia Dynasty (Rana Kumbha)',
      architecturalStyle: 'Mountain Ridgeline Defensive Bastion Wall',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Kumbhalgarh_055.jpg/1280px-Kumbhalgarh_055.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Kumbhalgarh_055.jpg/1280px-Kumbhalgarh_055.jpg',
      ],
      history: 'Constructed by Rana Kumbha, this fort possesses the second longest continuous wall in the world after the Great Wall of China (36 km), wide enough for eight horses to gallop abreast. It contains over 360 ancient temples and the Badal Mahal palace crowning the highest ridge.',
      folklore: 'Rana Kumbha would burn massive lamps requiring 50 kilograms of ghee and 100 kilograms of cotton to illuminate the valley below for local farmers working the fields at night.',
      bestTimeToVisit: 'Afternoon 3:00 PM through 7:30 PM for sunset and illuminated wall show',
      timings: '9:00 AM – 6:00 PM daily',
      entryFee: '₹40 (Indians), ₹600 (Foreigners)',
      howToReach: '85 km north of Udaipur in Rajsamand district. Best reached by private car or day-tour cab through scenic Aravalli passes.',
      giTagCraft: 'Mewari Hand-Carved Wooden Doors & Miniature Swords',
      isMajor: true,
      likesCount: 495,
      viewsCount: 4100,
    },
    {
      title: 'Ranakpur Jain Temple (Hidden)',
      slug: 'ranakpur-jain-temple',
      tagline: '1,444 uniquely carved white marble pillars nestled in a lush, secluded Aravalli forest valley',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Pali',
      latitude: 25.1158,
      longitude: 73.4739,
      century: '1437 CE',
      dynasty: 'Mewar Patronage (Seth Dharna Shah & Rana Kumbha)',
      architecturalStyle: 'Maru-Gurjara White Marble Temple Architecture',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Chaumukha_Jain_temple_at_Ranakpur_in_Aravalli_range_near_Udaipur_Rajasthan_India.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/8/86/Chaumukha_Jain_temple_at_Ranakpur_in_Aravalli_range_near_Udaipur_Rajasthan_India.jpg',
      ],
      history: 'Commissioned by wealthy merchant Dharna Shah following a divine vision, this sprawling marble temple took 50 years to sculpt under master artisan Depa. Out of 1,444 pillars, no two carvings are alike, yet they are aligned so that no column obstructs the view of the central Adinath idol.',
      folklore: 'Legend tells of a single intentionally tilted pillar near the sanctum, carved imperfectly so as not to invite the jealousy of the gods with mortal perfection.',
      bestTimeToVisit: '12:00 PM – 3:00 PM when sunlight dances through the marble colonnade',
      timings: '12:00 PM – 5:00 PM for non-Jain visitors',
      entryFee: '₹200 audio guide ticket',
      howToReach: '95 km from Udaipur and 50 km from Kumbhalgarh Fort. Often combined into a single day circuit from Udaipur.',
      giTagCraft: 'Pali Sandstone Lattice & Ranakpur White Marble Carvings',
      isMajor: false,
      likesCount: 440,
      viewsCount: 3600,
    },

    // ==========================================
    // 10. ALWAR, DAUSA & SARISKA
    // ==========================================
    {
      title: 'Chand Baori (Abhaneri)',
      slug: 'chand-baori-abhaneri',
      tagline: 'The world’s deepest stepwell: 3,500 hypnotic symmetrical steps cascading across 13 subterranean storeys',
      category: 'Stepwell',
      state: 'Rajasthan',
      district: 'Dausa',
      latitude: 27.0071,
      longitude: 76.6064,
      century: '8th–9th Century CE',
      dynasty: 'Nikumbha Dynasty (King Chanda)',
      architecturalStyle: 'Early Medieval Classical Stepped Reservoir',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Chand_Baori_perspective_panorama_%28July_2022%29.jpg/1280px-Chand_Baori_perspective_panorama_%28July_2022%29.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Chand_Baori_perspective_panorama_%28July_2022%29.jpg/1280px-Chand_Baori_perspective_panorama_%28July_2022%29.jpg',
      ],
      history: 'One of the oldest and deepest stepwells on Earth, Chand Baori descends 100 feet into the groundwater table. It served as a community cooling pavilion and sacred gathering sanctuary adjacent to the ancient Harshat Mata Temple.',
      folklore: 'Villagers still believe spirits built the 3,500 steps in a single night so no mortal could ever walk down and return on the same sequence.',
      bestTimeToVisit: 'October to February (Mid-morning for direct step shadows)',
      timings: '8:30 AM – 5:30 PM daily',
      entryFee: '₹25 (Indians), ₹300 (Foreign nationals)',
      howToReach: 'Located in Abhaneri village, 95 km from Jaipur off the Jaipur-Agra Highway (NH-21). Readily accessible by car or taxi.',
      giTagCraft: 'Dausa Terracotta Artifacts & Hand-Chiseled Sandstone Jali',
      isMajor: true,
      likesCount: 530,
      viewsCount: 4700,
    },
    {
      title: 'Bhangarh Fort Ruins (Hidden)',
      slug: 'bhangarh-fort-alwar',
      tagline: 'The atmospheric 17th-century ruined citadel at the edge of Sariska forest shrouded in desert legends',
      category: 'Forgotten Fort',
      state: 'Rajasthan',
      district: 'Alwar',
      latitude: 27.0967,
      longitude: 76.2867,
      century: '1573 CE',
      dynasty: 'Kachhwaha Rajput Dynasty (Bhagwant Das)',
      architecturalStyle: 'Medieval Stone Bazaars, Havelis, and Someshwar Temple',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Bhangarh_Fort_-_Royal_Palace_Bhangarh_%28July_2022%29_-_img_16.jpg/1280px-Bhangarh_Fort_-_Royal_Palace_Bhangarh_%28July_2022%29_-_img_16.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Bhangarh_Fort_-_Royal_Palace_Bhangarh_%28July_2022%29_-_img_16.jpg/1280px-Bhangarh_Fort_-_Royal_Palace_Bhangarh_%28July_2022%29_-_img_16.jpg',
      ],
      history: 'Built by Raja Bhagwant Das for his younger son Madho Singh, Bhangarh was once a bustling royal town with 10,000 dwellings, public stepwells, and ornate temples. Following severe military conflicts and population decline in the 1700s, the town was abandoned to nature and the surrounding Sariska tiger forest.',
      folklore: 'The famous legend of Tantrik Guru Singhia, who cursed the city after Princess Ratnavati spurned his magical love potion, led to ASI putting up a sign prohibiting entry after sunset.',
      bestTimeToVisit: 'Morning 9:00 AM – 1:00 PM during winter months',
      timings: '6:00 AM – 6:00 PM (Strictly closed after sunset per ASI regulations)',
      entryFee: '₹25 (Indians), ₹300 (Foreigners)',
      howToReach: '85 km from Jaipur and 90 km from Alwar. Accessible via Dausa-Gola Ka Baas road.',
      giTagCraft: 'Alwar Terracotta Pottery & Lac Artifacts',
      isMajor: false,
      likesCount: 395,
      viewsCount: 3400,
    },
    {
      title: 'Neelkanth Mahadev Temple Ruins in Sariska (Hidden)',
      slug: 'neelkanth-temple-sariska-alwar',
      tagline: 'Over 200 carved 10th-century stone temple ruins hidden deep inside the tiger reserve hills',
      category: 'Ancient Temple',
      state: 'Rajasthan',
      district: 'Alwar',
      latitude: 27.2789,
      longitude: 76.4411,
      century: '6th–10th Century CE',
      dynasty: 'Bargujar Rajput Kings (Maharajadhiraja Mathanadeva)',
      architecturalStyle: 'Khajuraho-Style Erotic & Tantric Sandstone Carvings',
      coverImage: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Neelkanth_temple%2C_Alwar_district.jpg',
      images: [
        'https://upload.wikimedia.org/wikipedia/commons/6/66/Neelkanth_temple%2C_Alwar_district.jpg',
      ],
      history: 'Standing secluded atop an isolated hill inside Sariska Tiger Reserve, Neelkanth was once a sprawling temple city. Today, the central Mahadev temple still survives with its monolithic black stone Shiva lingam, surrounded by hundreds of shattered carved apsaras, gandharvas, and monolithic statues.',
      folklore: 'Local Gujjar pastoralists narrate that wild leopards and tigers frequently walk through the temple courtyard at midnight without ever harming pilgrims who take refuge inside the sanctum.',
      bestTimeToVisit: 'October to March (Requires day safari pass into Sariska forest)',
      timings: '8:00 AM – 5:00 PM daily',
      entryFee: 'Free temple entry; forest entry token applies',
      howToReach: '32 km inside Sariska Tiger Reserve from Tehla Gate. Best accessed with a 4x4 Gypsy or high-clearance SUV.',
      giTagCraft: 'Sariska Forest Wild Honey & Rajasthani Folk Woodcraft',
      isMajor: false,
      likesCount: 230,
      viewsCount: 1680,
    }
  ];

  // Insert all places
  for (const place of placesData) {
    await prisma.place.create({ data: place });
  }

  console.log(`✅ Successfully seeded ${placesData.length} Rajasthan places with real verified images!`);

  // Seed Events in Rajasthan
  const eventsData = [
    {
      title: 'Pushkar International Camel & Cultural Fair',
      category: 'Folk Fair',
      location: 'Pushkar Mela Grounds',
      state: 'Rajasthan',
      startDate: new Date('2026-11-18'),
      endDate: new Date('2026-11-26'),
      description: 'One of the world’s largest camel and tribal livestock fairs, featuring colorful desert competitions, bridal competitions, folk concerts, and thousands of nomadic pastoralists under the Kartik Purnima full moon.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Evening_lights_by_the_Pushkar_Lake%2C_Pushkar.jpg/1280px-Evening_lights_by_the_Pushkar_Lake%2C_Pushkar.jpg',
      organizer: 'Rajasthan Tourism & Department of Animal Husbandry',
    },
    {
      title: 'Jodhpur RIFF (Rajasthan International Folk Festival)',
      category: 'Classical Dance',
      location: 'Mehrangarh Fort',
      state: 'Rajasthan',
      startDate: new Date('2026-10-24'),
      endDate: new Date('2026-10-28'),
      description: 'Held under the full moon in Mehrangarh Fort, uniting hereditary Manganiyar and Langa folk maestros with world-class international musicians on open stone ramparts.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Mehrangarh_Fort_sanhita.jpg',
      organizer: 'Mehrangarh Museum Trust & UNESCO',
    },
    {
      title: 'Bundi Utsav (Folk Heritage Festival)',
      category: 'Temple Festival',
      location: 'Chitrashala & Naval Sagar Lake',
      state: 'Rajasthan',
      startDate: new Date('2026-11-27'),
      endDate: new Date('2026-11-29'),
      description: 'A 3-day spectacle celebrating the stepwells and miniature art of Bundi with traditional turbanning competitions, Shobha Yatra processions, and deepotsav (floating oil lamps) on Nawal Sagar.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Rani_ji_ki_Baori_Bundi.jpg/1280px-Rani_ji_ki_Baori_Bundi.jpg',
      organizer: 'District Administration Bundi & Department of Tourism',
    }
  ];

  for (const ev of eventsData) {
    await prisma.event.create({ data: ev });
  }

  // Seed Stories in Rajasthan
  const storiesData = [
    {
      title: 'The Subterranean Water Engineers of the Thar Desert',
      author: 'Kunal Vaishnav & Hide Rajasthan Field Cell',
      state: 'Rajasthan',
      district: 'Bundi & Jodhpur',
      category: 'Water Architecture',
      summary: 'How ancient Rajasthani desert communities engineered stepwells and sand aquifers to survive centuries of extreme drought without modern plumbing.',
      content: 'In the hyper-arid geography of Rajasthan, water was not simply a resource; it was divinity. From Chand Baori in Abhaneri descending 13 subterranean storeys, to the communal stepwells of Bundi and Toorji Ka Jhalra in Jodhpur, Rajasthani architects developed hydraulic geometry that maximized rainwater harvesting while keeping the water sheltered from evaporation under punishing 48°C summer temperatures...',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Chand_Baori_perspective_panorama_%28July_2022%29.jpg/1280px-Chand_Baori_perspective_panorama_%28July_2022%29.jpg',
      tags: ['Stepwells', 'Baoris', 'Hydrology', 'Thar Desert'],
      readTimeMinutes: 5,
    },
    {
      title: 'The Vanishing Frescoes of Shekhawati: An Open-Air Gallery Under Threat',
      author: 'Hide Rajasthan Oral Heritage Archive',
      state: 'Rajasthan',
      district: 'Shekhawati',
      category: 'Folk Art',
      summary: 'Exploring the 700+ hand-painted havelis of Mandawa, Nawalgarh, and Fatehpur, and the urgent race to preserve their natural mineral pigments.',
      content: 'Between the 18th and early 20th centuries, wealthy Marwari merchants returning from Bombay and Calcutta channeled their fortunes into building painted palatial havelis in the semi-arid towns of Shekhawati. Local artisans used fresco buono techniques with natural lime plaster, mineral dyes, and gold foil to illustrate everything from Indian epics to the first steam locomotives and gramophones...',
      image: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Haveli_mandawa.jpg',
      tags: ['Shekhawati', 'Fresco Buono', 'Havelis', 'Mandawa'],
      readTimeMinutes: 6,
    }
  ];

  for (const st of storiesData) {
    await prisma.story.create({ data: st });
  }

  console.log('🎉 Rajasthan Seed Finished with Real Verified Images!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
